backend:
  name: github
  repo: BDEGUARDO/beatrizdeguardo-web
  branch: main
  auth_type: token

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "cuadros"
    label: "Cuadros"
    folder: "cuadros"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }
