backend:
  name: github
  repo: BDEGUARDO/beatrizdeguardo-web
  branch: main
  auth_type: implicit
  app_id: c2fbc1b6f15d932ea38a
  base_url: https://beatriz-de-guardo.netlify.app

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "figurativo"
    label: "Figurativo"
    folder: "content/figurativo"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Técnica", name: "technique", widget: "string", required: false }
      - { label: "Medidas", name: "size", widget: "string", required: false }
      - { label: "Descripción", name: "body", widget: "markdown", required: false }

  - name: "abstracto"
    label: "Abstracto"
    folder: "content/abstracto"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Técnica", name: "technique", widget: "string", required: false }
      - { label: "Medidas", name: "size", widget: "string", required: false }
      - { label: "Descripción", name: "body", widget: "markdown", required: false }

  - name: "etnico"
    label: "Étnico"
    folder: "content/etnico"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Técnica", name: "technique", widget: "string", required: false }
      - { label: "Medidas", name: "size", widget: "string", required: false }
      - { label: "Descripción", name: "body", widget: "markdown", required: false }

  - name: "eterico"
    label: "Figurativo etérico"
    folder: "content/eterico"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Imagen", name: "image", widget: "image" }
      - { label: "Técnica", name: "technique", widget: "string", required: false }
      - { label: "Medidas", name: "size", widget: "string", required: false }
      - { label: "Descripción", name: "body", widget: "markdown", required: false }

  - name: "poesia"
    label: "Poesía"
    folder: "content/poesia"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Contenido", name: "body", widget: "markdown" }

  - name: "bio"
    label: "Sobre la artista"
    files:
      - file: "content/sobre-la-artista.md"
        label: "Biografía"
        name: "biografia"
        fields:
          - { label: "Título", name: "title", widget: "string" }
          - { label: "Texto", name: "body", widget: "markdown" }
