backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "cuadros"
    label: "Cuadros"
    folder: "content/cuadros"
    create: true
    delete: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Técnica", name: "technique", widget: "string" }
      - { label: "Medidas", name: "size", widget: "string" }
      - {
          label: "Categoría",
          name: "category",
          widget: "select",
          options: ["Figurativo", "Abstracto", "Étnico", "Figurativo etérico"]
        }
      - { label: "Descripción", name: "description", widget: "text" }
      - { label: "Imagen", name: "image", widget: "image" }